name: mac_mobile_attempt
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.1.0 <3.0.0"
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_multiselect: 0.0.1
  googleapis: any
  googleapis_auth: any
  url_launcher: ^5.0.3
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  image_ink_well: ^0.1.0
  shared_preferences: ^0.4.2
  intl: ^0.15.8
  flutter_screenutil: ^0.5.0
  get_it: ^1.0.3+2




    
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  date_utils: ^0.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
flutter_icons:
  image_path: "assets/icon/project_icon.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/1600.png
    - assets/images/1600new.png
    - assets/images/moodle.png
    - assets/images/moodlenew.png
    - assets/images/class.png
    - assets/images/classnew.png
    - assets/images/academic.png
    - assets/images/academicnew.png
    - assets/images/maclogo.jpg
    - assets/images/snow.jpg

    - assets/images/map.png
    - assets/images/security.png
    - assets/images/security2.png
    - assets/images/organizations.gif
    - assets/images/residence.jpg
    - assets/images/1600.gif
    - assets/images/moodle.gif
    - assets/images/class2.jpg
    - assets/images/calendar.gif
    - assets/images/maxcenter.gif    
    - assets/images/library.gif    
    - assets/images/handshake.jpg
    - assets/images/appointment.jpg



    - assets/maxresdefault.jpg
    - assets/cafemac.jpg
    - assets/campuscenter.jpg
    - assets/centralstores.jpg
    - assets/digitalresourcecenter.jpg
    - assets/leonardcenter.jpg
    - assets/healthandwellness.jpg
    - assets/ITS.jpg
    - assets/library.jpg
    - assets/mailingservices.jpg
    - assets/studentaccounts.jpg
    - assets/highlander.jpg
    - assets/oldmain.jpg
    - assets/hourspage.jpg
    - assets/homepage.jpg
    - assets/images/loch.jpg
    - assets/images/atrium.jpg
    - assets/images/scottys.png
    - assets/images/coffeecart.jpg
    - assets/images/diningheader.jpg

    - assets/macLogo2.png
    - assets/images/mac-primary-logo-spot blue.png
    - assets/images/mac-sec-horizontal-logo-spot.png
    - assets/images/mac-sec-horizontal-logo-k.png
    - assets/images/dining.jpg
    - assets/images/grille.jpg
    - assets/images/scottys.jpeg
    - assets/images/cafemacbeautismall.jpg
    - assets/images/HPnew.jpg
    - assets/images/highlandernew.jpg
    - assets/images/jwal.jpg
    - assets/images/ccnew.jpg
    - assets/images/jwalblue.jpg
    - assets/images/pool.jpg
    - assets/images/pool2.jpg
    - assets/images/lc.jpg
    - assets/images/lc2.jpg
    - assets/images/hwc2.jpg



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
